# config/setting.py
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import environ
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- env 설정 추가 ---
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
# ----------------------

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# LLM 호출용. 없으면 상담 답변 생성이 실패한다 (서버는 뜬다).
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')

SECRET_KEY = env('SECRET_KEY', default='dev-only-insecure-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

# 배포 도메인은 환경변수로 받는다 (콤마 구분).
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# ALB/CloudFront 뒤에 있을 때 원본 스킴을 신뢰한다.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    # 기본 앱들
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party 패키지
    'rest_framework',
    'corsheaders',
    'drf_spectacular',

    # Local Apps (직접 만든 앱들)
    'users',
    'chat',
    'llm_core',
    'scripture',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 로컬에서 DATABASE_URL 이 없으면 SQLite 로 떨어진다 — 첫 실행 장벽을 없앤다.
DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'     # 언어코드 설정

TIME_ZONE = 'Asia/Seoul'    # 시간 기준 나라 설정

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 모델 기본 PK 타입. 지정하지 않으면 앱마다 경고가 뜬다.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = 'static/'
# collectstatic 대상. Nginx 가 이 디렉터리를 직접 서빙한다.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Custom User Model 설정
AUTH_USER_MODEL = 'users.User'

# React, Vite 등 프론트엔드 개발 서버 주소 허용
# 개발 모드에서 허용할 프론트엔드 도메인/포트 목록
# 배포 도메인(CloudFront)은 환경변수로 덧붙인다.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   # CRA / Next 개발 서버
    "http://127.0.0.1:3000",
    "http://localhost:5173",   # Vite 개발 서버
    "http://127.0.0.1:5173",
    "http://localhost:4173",   # Vite preview
] + env.list('CORS_ALLOWED_ORIGINS', default=[])

# CSRF 는 CORS 와 별개다. 폼 전송이 없더라도 admin 로그인에 필요하다.
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# 인증 정보(Cookie, Authorization 헤더 등)를 포함한 요청 허용
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework 기본 설정 (추후 Swagger 및 JWT 세팅 시 활용)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # 목록이 길어지는 API 는 개별 뷰에서 pagination_class = None 으로 끈다.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,

    # 남용 방지. 익명은 분당 60회, 로그인 사용자는 분당 120회.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '120/min',
    },
}

# Swagger / drf-spectacular 상세 설정 추가
SPECTACULAR_SETTINGS = {
    'TITLE': 'Chatbot Service API',
    'DESCRIPTION': 'Django 기반 AI 챗봇 백엔드 API 문서입니다.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Swagger Authorize 버튼 클릭 시 Bearer가 자동으로 붙도록 설정
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,  # 새로고침해도 인증 유지
    },
}

# JWT 설정 (토큰 유효기간 및 헤더 설정)  
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),   # Access Token 유효기간 1일
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh Token 유효기간 7일
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ── SSE(실시간 스트리밍) 관련 ─────────────────────────────────────────
#
# 상담 답변은 text/event-stream 으로 한 글자씩 내려간다.
#
# ★ 프록시가 버퍼링하면 스트리밍이 아니라 "한참 뒤에 한꺼번에"가 된다.
#   chat/views.py 가 응답마다 X-Accel-Buffering: no 를 붙이지만,
#   Nginx 앞단에도 proxy_buffering off 가 필요하다 (deploy/nginx.conf).
#
# ★ 배포 시 WSGI 워커가 동기식이면 스트리밍 중 워커 하나가 묶인다.
#   gunicorn 은 --worker-class gthread 로 띄운다.
