# Generated by Django 5.2.16 on 2026-08-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mbti',
            field=models.CharField(blank=True, choices=[('INFJ', 'INFJ'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP')], max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
