# Generated by Django 5.2.16 on 2026-08-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=64)),
                ('mbti', models.CharField(max_length=4)),
                ('tint', models.CharField(blank=True, max_length=7)),
                ('is_center', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': '은하',
                'verbose_name_plural': '은하',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('book_code', models.CharField(max_length=8)),
                ('book_name', models.CharField(max_length=16)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('depth', models.CharField(choices=[('full', '큐레이션'), ('brief', '연관 구절')], default='brief', max_length=8)),
                ('summary', models.TextField()),
                ('themes', models.JSONField(default=list)),
                ('motif', models.CharField(max_length=16)),
                ('magnitude', models.FloatField(default=0.5)),
                ('excerpt', models.CharField(blank=True, max_length=120)),
                ('attribution', models.CharField(blank=True, max_length=32)),
                ('story', models.TextField(blank=True)),
                ('meditation', models.TextField(blank=True)),
                ('related_prompts', models.JSONField(blank=True, default=list)),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='scripture.galaxy')),
            ],
            options={
                'verbose_name': '구절',
                'verbose_name_plural': '구절',
                'ordering': ['galaxy__order', 'order'],
                'indexes': [models.Index(fields=['depth'], name='scripture_v_depth_46edeb_idx'), models.Index(fields=['galaxy', 'order'], name='scripture_v_galaxy__9c20ec_idx')],
            },
        ),
    ]
