# Generated by Django 5.2.16 on 2026-08-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0003_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('book_code', models.CharField(max_length=8)),
                ('book_order', models.PositiveSmallIntegerField()),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('tone', models.CharField(db_index=True, default='neutral', max_length=8)),
            ],
            options={
                'verbose_name': '성경 구절',
                'verbose_name_plural': '성경 구절',
                'ordering': ['book_order', 'chapter', 'verse'],
                'indexes': [models.Index(fields=['book_code', 'chapter'], name='scripture_b_book_co_cf95f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('book_code', 'chapter', 'verse'), name='unique_bible_verse')],
            },
        ),
    ]
