# Generated by Django 5.2.16 on 2026-08-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0005_bibleverse_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleverse',
            name='galaxy_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='on_canvas',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='usable',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
