# Generated by Django 5.2.16 on 2026-08-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0006_bibleverse_galaxy_id_bibleverse_on_canvas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=120)),
                ('dim', models.PositiveIntegerField()),
                ('verses', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '임베딩 적재 기록',
                'verbose_name_plural': '임베딩 적재 기록',
            },
        ),
    ]
