# Generated by Django 5.2.16 on 2026-08-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_id_alter_chatsession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='persona_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
