# Generated by Django 5.2.16 on 2026-08-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_persona_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='persona_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
