# Generated by Django 5.2.16 on 2026-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatsession_persona_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='seed_verse_ref',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
